### ISSUE TITLE
TODO till launch

### ISSUE THREAD

**Issue by tomek-he-him** [tomekwi/present-now#1]
* [x] `<timer-controls>` bundle
* [x] app shell with title and progress bar
* [x] port + event for initial color
* [x] `<timer-display>` with single color
* [x] switching between screens
* [x] code chunking + prefetching
* [x] controls + events for further colors
* [x] `<timer-display>` for further colors
* [ ] offline support
* [ ] PWA goodies
* [x] pause button

**Comment by hinok** [comment]
@tomekwi Hey, I was at the last React meetup in Wroclaw, I propose adding ESC key handler which will trigger pause action and maybe support swipe gestures on handheld devices. I couldn't find pause button for the first few seconds. That's from me.

P.S. interesting presentation!

**Comment by tomek-he-him** [comment]
Thanks a lot @hinok, very glad you liked the talk!

Super valid points about the keyboard handlers and UX issues. For us, this has been more of a proof of concept than a polished app – but if you like the app and end up using it regularly, we *love* PRs! 😄

**Comment by tomek-he-him** [comment]
Closing off this issue for now, because this was a roadmap before the talk rather than something we should actually fix. Most of it is done by now, just short of ✨ offline support.
